export { getDateName, getMonthPeriod, unixToHours } from './date'
export { fetchData } from './WeatherAPI'
export { fetchCities } from './WeatherAPI'
export { default as getCountryName } from './countries'
export { default as getIconName } from './icons'
export { default as getTemp } from './temp'
